<?php
/**
 * @package   Options Module
 * @author    Riccardo D'Angelo <riccardo@waga.it>, WAGA <dev@waga.it>
 * @license   GPL-2.0+
 * @link      http://www.waboot.com
 * @copyright WAGA.it
 *
 * Based on Devin Price' Options_Framework
 */

namespace WBF\modules\options;

class CodeEditor {
	static function optionsframework_codeditor( $_id, $_value, $_desc = '', $_name = '', $_lang = 'css' ) {
		$optionsframework_settings = get_option( 'optionsframework' );

		// Gets the unique option id
		$option_name = $optionsframework_settings['id'];

		$output = '';
		$id     = '';
		$class  = '';
		$int    = '';
		$value  = '';
		$name   = '';

		$id = strip_tags( strtolower( $_id ) );

		// If a value is passed and we don't have a stored value, use the value that's passed through.
		if ( $_value != '' && $value == '' ) {
			$value = $_value;
		}

		if ( $_name != '' ) {
			$name = $_name;
		} else {
			$name = $option_name . '[' . $id . ']';
		}

		$class = "of-input codemirror";

		$output .= "<textarea id='$id' class='$class' name='$name' data-lang='$_lang' rows='8'>$value</textarea>";

		/*$output .= "<script>
		var editor = CodeMirror.fromTextArea(document.getElementById('{$id}'), {
		  mode: 'css',
		  lineNumbers: true
		});
		</script>";*/

		return $output;
	}

	public function init() {
		add_action( 'admin_enqueue_scripts', array( $this, 'optionsframework_codeditor_scripts' ) );
		add_action( 'updated_option', array( $this, 'optionsframework_codeditor_save' ), 10, 3 );
	}

	/**
	 * Get all options that are registered as css editor
	 */
	public function get_csseditor_options(){
		$options = Framework::get_registered_options();
		$css_editor_options = [];
		foreach($options as $opt){
			if(isset($opt['type']) && isset($opt['name']) && isset($opt['id']) && $opt['type'] == "csseditor"){
				$css_editor_options[] = $opt['id'];
			}
		}
		return $css_editor_options;
	}

	function optionsframework_codeditor_scripts( $hook ) {
		if(!of_is_admin_framework_page($hook)){
			return;
		}

        wp_register_script('codemirror', WBF_URL . '/vendor/codemirror/lib/codemirror.js');
        wp_register_style('codemirror-css', WBF_URL . '/vendor/codemirror/lib/codemirror.css');
        /*if(WBF_ENV == "dev"){
            wp_register_script('of-waboot-codeditor', WBF_URL . '/assets/src/js/admin/code-editor.js', array('jquery', 'codemirror', 'underscore'), Framework::VERSION );
        }else{
            wp_register_script('of-waboot-codeditor', WBF_URL . '/admin/js/code-editor.min.js', array('jquery', 'codemirror', 'underscore'), Framework::VERSION );
        }*/
		//Modes
        wp_register_script('codemirror-mode-css', WBF_URL . '/vendor/codemirror/mode/css/css.js', array('codemirror'));

		//Addons
        wp_register_script('codemirror-addon-hint', WBF_URL . '/vendor/codemirror/addon/hint/show-hint.js');
        wp_register_style('codemirror-addon-hint-style', WBF_URL . '/vendor/codemirror/addon/hint/show-hint.css');
        wp_register_script('codemirror-addon-hint-css', WBF_URL . '/vendor/codemirror/addon/hint/css-hint.js', array(
				'codemirror',
				'codemirror-addon-hint'
			) );

		//Themes
        wp_register_style('codemirror-theme-ambiance', WBF_URL . '/vendor/codemirror/theme/ambiance.css');

		/**
		 * Enqueues
		 */
		wp_enqueue_script( 'codemirror' );
		wp_enqueue_style( 'codemirror-css' );

		wp_enqueue_script( 'codemirror-mode-css' );
		wp_enqueue_script( 'codemirror-addon-hint' );
		wp_enqueue_style( 'codemirror-addon-hint-style' );
		wp_enqueue_script( 'codemirror-addon-hint-css' );
		wp_enqueue_style( 'codemirror-theme-ambiance' );

		//wp_enqueue_script( 'of-waboot-codeditor' );
	}

	/**
	 * Save the custom editor values to a file
	 *
	 * @hooked 'updated_option'
	 *
	 * @param $option
	 * @param $old_value
	 * @param $value
	 */
	function optionsframework_codeditor_save( $option, $old_value, $value ) {
        if(!is_admin()) return;
		if(is_array($value)){
			$valid_options = $this->get_csseditor_options();
			foreach($valid_options as $opt_id){
				if(array_key_exists($opt_id,$value)){
					$content[] = $value[$opt_id];
				}
			}
			if(isset($content) && is_array($content)){
				$new_css = implode("\n",$content);
				$filename = "client-custom.css"; //todo: make file name customizable
				$filepath = WBF_OPTIONS_FRAMEWORK_THEME_ASSETS_DIR."/".$filename;
				if(is_dir(dirname($filepath))){
					$result = file_put_contents( $filepath, $new_css );
				}
			}
		}
	}

	/**
	 * Checks if there is an autogenerated custom client css file and returns it. Returns FALSE otherwise.
	 *
	 * @return string|bool
	 */
	static function custom_css_exists() {
		$filepath = WBF_OPTIONS_FRAMEWORK_THEME_ASSETS_DIR."/client-custom.css"; //todo: make file name customizable
		if (is_file($filepath)) {
			return $filepath;
		}
		return false;
	}
}